//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.261
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hero.Language {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hero.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 購買訊息 的當地語系化字串。
        /// </summary>
        public static string GMENU_B {
            get {
                return ResourceManager.GetString("GMENU_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您確定要花費$9500購買戰機？ 的當地語系化字串。
        /// </summary>
        public static string GMENU_BUYLIFE {
            get {
                return ResourceManager.GetString("GMENU_BUYLIFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您確定要花費$4800購買能力值點數？ 的當地語系化字串。
        /// </summary>
        public static string GMENU_BUYR {
            get {
                return ResourceManager.GetString("GMENU_BUYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 購買能力值 的當地語系化字串。
        /// </summary>
        public static string GMENU_D1 {
            get {
                return ResourceManager.GetString("GMENU_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 購買戰機 的當地語系化字串。
        /// </summary>
        public static string GMENU_D2 {
            get {
                return ResourceManager.GetString("GMENU_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始戰鬥 的當地語系化字串。
        /// </summary>
        public static string GMENU_D3 {
            get {
                return ResourceManager.GetString("GMENU_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輕鬆 的當地語系化字串。
        /// </summary>
        public static string GMENU_EASY {
            get {
                return ResourceManager.GetString("GMENU_EASY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 困難 的當地語系化字串。
        /// </summary>
        public static string GMENU_HARD {
            get {
                return ResourceManager.GetString("GMENU_HARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 能力值點數： 的當地語系化字串。
        /// </summary>
        public static string GMENU_M1 {
            get {
                return ResourceManager.GetString("GMENU_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分數： 的當地語系化字串。
        /// </summary>
        public static string GMENU_M2 {
            get {
                return ResourceManager.GetString("GMENU_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金幣： 的當地語系化字串。
        /// </summary>
        public static string GMENU_M3 {
            get {
                return ResourceManager.GetString("GMENU_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 戰機 × 的當地語系化字串。
        /// </summary>
        public static string GMENU_M4 {
            get {
                return ResourceManager.GetString("GMENU_M4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sorry！金幣不足！ 的當地語系化字串。
        /// </summary>
        public static string GMENU_NO {
            get {
                return ResourceManager.GetString("GMENU_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 正常 的當地語系化字串。
        /// </summary>
        public static string GMENU_NORMAL {
            get {
                return ResourceManager.GetString("GMENU_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 攻擊傷害 的當地語系化字串。
        /// </summary>
        public static string GMENU_S1 {
            get {
                return ResourceManager.GetString("GMENU_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發射速度 的當地語系化字串。
        /// </summary>
        public static string GMENU_S2 {
            get {
                return ResourceManager.GetString("GMENU_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 子彈數量 的當地語系化字串。
        /// </summary>
        public static string GMENU_S3 {
            get {
                return ResourceManager.GetString("GMENU_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 抵擋及移動 的當地語系化字串。
        /// </summary>
        public static string GMENU_S4 {
            get {
                return ResourceManager.GetString("GMENU_S4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HP 的當地語系化字串。
        /// </summary>
        public static string GMENU_S5 {
            get {
                return ResourceManager.GetString("GMENU_S5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統訊息 的當地語系化字串。
        /// </summary>
        public static string MENU_MSG {
            get {
                return ResourceManager.GetString("MENU_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新的遊戲會將您上次的遊戲紀錄給清除！？ 的當地語系化字串。
        /// </summary>
        public static string MENU_MSGC {
            get {
                return ResourceManager.GetString("MENU_MSGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新　遊　戲 的當地語系化字串。
        /// </summary>
        public static string MENU_NEWGAME {
            get {
                return ResourceManager.GetString("MENU_NEWGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀　取　遊　戲 的當地語系化字串。
        /// </summary>
        public static string MENU_READ {
            get {
                return ResourceManager.GetString("MENU_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遊　戲　分　數 的當地語系化字串。
        /// </summary>
        public static string MENU_SCORE {
            get {
                return ResourceManager.GetString("MENU_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遊　戲　教　學 的當地語系化字串。
        /// </summary>
        public static string MENU_TEACH {
            get {
                return ResourceManager.GetString("MENU_TEACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關　於　作　者 的當地語系化字串。
        /// </summary>
        public static string MENU_WRITER {
            get {
                return ResourceManager.GetString("MENU_WRITER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最高分數 的當地語系化字串。
        /// </summary>
        public static string SCORE_1 {
            get {
                return ResourceManager.GetString("SCORE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排 名 的當地語系化字串。
        /// </summary>
        public static string SCORE_1A {
            get {
                return ResourceManager.GetString("SCORE_1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分 數 的當地語系化字串。
        /// </summary>
        public static string SCORE_1B {
            get {
                return ResourceManager.GetString("SCORE_1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 歷史分數 的當地語系化字串。
        /// </summary>
        public static string SCORE_2 {
            get {
                return ResourceManager.GetString("SCORE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日期時間 的當地語系化字串。
        /// </summary>
        public static string SCORE_2A {
            get {
                return ResourceManager.GetString("SCORE_2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關卡 的當地語系化字串。
        /// </summary>
        public static string SCORE_2B {
            get {
                return ResourceManager.GetString("SCORE_2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分數 的當地語系化字串。
        /// </summary>
        public static string SCORE_2C {
            get {
                return ResourceManager.GetString("SCORE_2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遊戲分數 的當地語系化字串。
        /// </summary>
        public static string SCORE_TITLE {
            get {
                return ResourceManager.GetString("SCORE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輕鬆玩 的當地語系化字串。
        /// </summary>
        public static string SELECT_EASY {
            get {
                return ResourceManager.GetString("SELECT_EASY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 困難，我想挑戰！ 的當地語系化字串。
        /// </summary>
        public static string SELECT_HARD {
            get {
                return ResourceManager.GetString("SELECT_HARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 正常 的當地語系化字串。
        /// </summary>
        public static string SELECT_NORMAL {
            get {
                return ResourceManager.GetString("SELECT_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確　定 的當地語系化字串。
        /// </summary>
        public static string SELECT_OK {
            get {
                return ResourceManager.GetString("SELECT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  請選擇難易度： 的當地語系化字串。
        /// </summary>
        public static string SELECT_TITLE {
            get {
                return ResourceManager.GetString("SELECT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 返　回 的當地語系化字串。
        /// </summary>
        public static string STOP_BACK {
            get {
                return ResourceManager.GetString("STOP_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 離開遊戲 的當地語系化字串。
        /// </summary>
        public static string STOP_EXIT {
            get {
                return ResourceManager.GetString("STOP_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 戰機移動 的當地語系化字串。
        /// </summary>
        public static string TEACH_M1 {
            get {
                return ResourceManager.GetString("TEACH_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發射子彈 的當地語系化字串。
        /// </summary>
        public static string TEACH_M2 {
            get {
                return ResourceManager.GetString("TEACH_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得寶物 的當地語系化字串。
        /// </summary>
        public static string TEACH_M3 {
            get {
                return ResourceManager.GetString("TEACH_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星星勳章 的當地語系化字串。
        /// </summary>
        public static string TEACH_M4 {
            get {
                return ResourceManager.GetString("TEACH_M4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 戰機防禦 的當地語系化字串。
        /// </summary>
        public static string TEACH_M5 {
            get {
                return ResourceManager.GetString("TEACH_M5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遊戲教學 的當地語系化字串。
        /// </summary>
        public static string TEACH_TITLE {
            get {
                return ResourceManager.GetString("TEACH_TITLE", resourceCulture);
            }
        }
    }
}
